services:
  app:
    image:  "${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/techpro-rental-car:latest"
    container_name: flask-app
    restart: always
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=my_secret_key
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_HOST=db
      - DB_NAME=araba_kiralama
    ports:
      - "8000:8000"
    depends_on:
      - db
    # volumes:
    #   - ./App:/app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Rp123456
      MYSQL_DATABASE: araba_kiralama
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: nginx-container
    environment:
      - DOMAIN_NAME=techprodevops.com
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    ports:
      - "80:80"

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
